# Generated by Django 5.2.3 on 2025-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
